// <auto-generated />
using Mango.Services.CouponAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.CouponAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.CouponAPI.Models.Coupon", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "10OFF",
                            DiscountAmount = 10.0,
                            MinAmount = 30
                        },
                        new
                        {
                            Id = 2L,
                            Code = "30OFF",
                            DiscountAmount = 30.0,
                            MinAmount = 80
                        },
                        new
                        {
                            Id = 3L,
                            Code = "50OFF",
                            DiscountAmount = 5.0,
                            MinAmount = 15
                        },
                        new
                        {
                            Id = 4L,
                            Code = "6OFF",
                            DiscountAmount = 6.0,
                            MinAmount = 18
                        },
                        new
                        {
                            Id = 5L,
                            Code = "7OFF",
                            DiscountAmount = 7.0,
                            MinAmount = 21
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
